CREATE TABLE `einvoice_documents` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`invoice_id` integer NOT NULL,
	`doc_type` text DEFAULT 'INV' NOT NULL,
	`supply_category` text DEFAULT 'B2C' NOT NULL,
	`irn` text,
	`ack_no` text,
	`ack_date` text,
	`signed_qr_code` text,
	`qr_content` text,
	`payload_json` text,
	`gateway` text DEFAULT 'LOCAL' NOT NULL,
	`irp_registered` integer DEFAULT 0 NOT NULL,
	`status` text DEFAULT 'PREPARED' NOT NULL,
	`cancel_reason` text,
	`cancelled_at` text,
	`error_message` text,
	`created_by` integer,
	`created_at` text DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (`invoice_id`) REFERENCES `invoices`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `ewaybills` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`invoice_id` integer NOT NULL,
	`eway_bill_number` text,
	`eway_date` text,
	`valid_until` text,
	`transport_mode` text DEFAULT 'ROAD' NOT NULL,
	`vehicle_number` text,
	`transporter_id` text,
	`transporter_name` text,
	`distance_km` integer DEFAULT 0 NOT NULL,
	`from_pincode` text,
	`to_pincode` text,
	`payload_json` text,
	`gateway` text DEFAULT 'LOCAL' NOT NULL,
	`status` text DEFAULT 'PREPARED' NOT NULL,
	`cancel_reason` text,
	`cancelled_at` text,
	`error_message` text,
	`created_by` integer,
	`created_at` text DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (`invoice_id`) REFERENCES `invoices`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
